version: '2'

services:
  minor.cursusbeheer:
    image: minor.cursusbeheer:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "80:80"
    environment:
      - REMOTE_DEBUGGING
