// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Case1.FrontEnd.FrontEnd.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CursusInstantie
    {
        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie() { }

        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie(int? id = default(int?), string cursusId = default(string), DateTime startDatum = default(DateTime), Cursus cursus = default(Cursus))
        {
            Id = id;
            CursusId = cursusId;
            StartDatum = startDatum;
            Cursus = cursus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursusId")]
        public string CursusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDatum")]
        public DateTime StartDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursus")]
        public Cursus Cursus { get; set; }

    }
}
