// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Case1.FrontEnd.FrontEnd.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DateModel
    {
        /// <summary>
        /// Initializes a new instance of the DateModel class.
        /// </summary>
        public DateModel() { }

        /// <summary>
        /// Initializes a new instance of the DateModel class.
        /// </summary>
        public DateModel(DateTime? startDatum = default(DateTime?), DateTime? eindDatum = default(DateTime?), int? jaar = default(int?), int? week = default(int?))
        {
            StartDatum = startDatum;
            EindDatum = eindDatum;
            Jaar = jaar;
            Week = week;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDatum")]
        public DateTime? StartDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eindDatum")]
        public DateTime? EindDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jaar")]
        public int? Jaar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "week")]
        public int? Week { get; set; }

    }
}
