// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DemoClient.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Slak
    {
        /// <summary>
        /// Initializes a new instance of the Slak class.
        /// </summary>
        public Slak() { }

        /// <summary>
        /// Initializes a new instance of the Slak class.
        /// </summary>
        public Slak(long? id = default(long?), string naam = default(string))
        {
            Id = id;
            Naam = naam;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "naam")]
        public string Naam { get; set; }

    }
}
