version: '2'

services:
  minor.cursussite:
    image: minor.cursussite:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "80:80"
    environment:
      - REMOTE_DEBUGGING
