// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.CursuSite.Cursusbeheer.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Cursus
    {
        /// <summary>
        /// Initializes a new instance of the Cursus class.
        /// </summary>
        public Cursus() { }

        /// <summary>
        /// Initializes a new instance of the Cursus class.
        /// </summary>
        public Cursus(long? id = default(long?), string naam = default(string), int? duur = default(int?))
        {
            Id = id;
            Naam = naam;
            Duur = duur;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "naam")]
        public string Naam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duur")]
        public int? Duur { get; set; }

    }
}
